# Title: ums-proxy-stack
# Description: Bittorrent client behind Wireguard Proxy via Mullvad VPN for the Ultimate Media Stack
# Icon URL: https://upload.wikimedia.org/wikipedia/commons/a/ae/The_Hydra_Bay_logo.png
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard
    privileged: true
    container_name: ums-wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - SERVERURL=ums-proxy.molovestoshare.com
    volumes:
      - /mnt/docker/volumes/wireguard/wireguard-client:/config
      - /lib/modules:/lib/modules
    ports:
    - 8112:8112
    - 6881:6881
    - 51820:51820
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped   
    labels:
      org.label-schema.group: "ums"
      com.centurylinklabs.watchtower.enable: "true"
  deluge:
    privileged: true
    image: lscr.io/linuxserver/deluge
    container_name: ums-deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:deluge
      - TP_COMMUNITY_THEME=true
      - TP_THEME=onedark
    volumes:
      - deluge_data:/config
      - /mnt/tf_nfsdisk/Media/downloads:/downloads
    network_mode: service:wireguard
    restart: unless-stopped
    labels:
      org.label-schema.group: "ums"
      com.centurylinklabs.watchtower.enable: "true"

volumes:
  deluge_data: {}  

networks:
  default:
    name: proxynet
    external: true