version: '3'

services:
  telegraf:
    image: telegraf:1.25-alpine
    container_name: telegraf
    hostname: telegraf
    depends_on:
      - influxdb
    volumes:
      - telegraf_data:/var/lib/telegraf:rw
      # - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro #only uncomment when seeding
    command: ["--config", "/var/lib/telegraf/telegraf.conf"]
    ports:
      - "8125:8125"
      - "8126:8126"
    cap_add:
      - NET_RAW
      - NET_BIND_SERVICE
    security_opt:
      - apparmor:unconfined

  grafana:
    # env_file:
      # - influxv2.env
    image: grafana/grafana-oss #grafana/grafana:9.5.17
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    environment:
      GRAFANA_USER: "${GF_SECURITY_ADMIN_USER:-admin}"
      GRAFANA_PASSWORD: "${GF_SECURITY_ADMIN_PASSWORD:-admin_pass}"
      GF_PLUGINS_ALLOW_LOCAL_MODE: true
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana  # Mount the Grafana data directory

  influxdb:
    image: influxdb:2.6-alpine
    container_name: influxdb
    hostname: influxdb
    # env_file:
      # - influxv2.env
    volumes:
      - influxdbv2_data:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"

volumes:
  influxdbv2_data:
  grafana_data:
  telegraf_data: