global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: prometheus
  scrape_interval: 15s
  scrape_timeout: 10s
  scheme: http
  honor_timestamps: true
  static_configs:
    - targets: ['localhost:9090']
  metrics_path: /grafpromon
- job_name: node-exporter
  static_configs:
    - targets: ['node_exporter:9100']
  honor_timestamps: true
- job_name: cadvisor
  static_configs:
    - targets: ['cadvisor:8098']
  honor_timestamps: true