global:
  scrape_interval: 15s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
# A scrape configuration containing exactly one endpoint to scrape each
- job_name: 'statping'
  scheme: https
  scrape_interval: 30s
  bearer_token: 'YOUR-API-KEY'
  static_configs:
    - targets: ['appstatus.molovestoshare.com']
- job_name: prometheus
  scrape_interval: 15s
  scheme: http
  honor_timestamps: true
  static_configs:
    - targets: ['prometheus:9090']
  # metrics_path: /grafpromon # metrics_path defaults to '/metrics'
- job_name: node-exporter
  static_configs:
    - targets: ['node_exporter:9100']
  honor_timestamps: true
- job_name: tf_node_exporter
  static_configs:
    - targets: ['192.168.50.239:9100']
  honor_timestamps: true
- job_name: th_cadvisor
  static_configs:
    - targets: ['cadvisor:8098']
  honor_timestamps: true
- job_name: tf_cadvisor
  static_configs:
    - targets: ['192.168.50.239:8098']
  honor_timestamps: true
