- targets:  # url;humanname;routing;switch
    - https://diamondbodyart.molovestoshare.com/diamondbodyart;external;internetbox
    - https://homebridge.molovestoshare.com;homebridge;external;internetbox
    - https://plex.molovestoshare.com;plex;external;internetbox
    - https://netdata.molovestoshare.com;netdata;external;internetbox
    - https://dbotz.molovestoshare.com;DlooGE;external;internetbox
    - https://nextcloud.molovestoshare.com;nextcloud;external;internetbox
    - https://grafana.molovestoshare.com;grafana;external;internetbox
    - https://organizr.molovestoshare.com;organizr;external;internetbox
    - https://192.168.10.254;internetbox;local;internetbox