# Title:
# Description: Plex Media Server
# IconURL: https://play-lh.googleusercontent.com/F39M_Ce9OBW62qntNOq6jvUH3Nh0N-03eGNFFU14GAU-hCU0RlHBONYYBiS-0SY0kaY
---
version: '3.9'

volumes:
  plex_data: {}

services:
  plex:
    privileged: true
    image: lscr.io/linuxserver/plex
    container_name: ums-plex
    hostname: ums-plex
    domainname: plex.molovestoshare.com
    cap_add:
      - DAC_READ_SEARCH
      - SYS_ADMIN
    environment:
      - PLEX_UID=${PUID:-1000}
      - PLEX_GID=${GUID:-1000}
      - VERSION=docker
      - TZ="America/Chicago"
      - runtime=nvidia
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:plex
      - TP_DOMAIN=themepark.molovestoshare.com
      - TP_THEME=overseerr
      # - PLEX_CLAIM= # Generate new claim codes here: https://www.plex.tv/claim/
      # - ADVERTISE_IP= # dont forget to add '/web' to the url
    volumes:
      - /tmp:/transcodes
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
      - plex_data:/config
      - /mnt/tf_nfsdisk/Media/tv-shows:/TV Shows
      - /mnt/tf_nfsdisk/Media/movies:/Movies
    network_mode: host
    ports:
      - 192.168.50.238:32400:32400
      - 192.168.50.238::1900/udp
      - 192.168.50.238::3005
      - 192.168.50.238::5353/udp
      - 192.168.50.238::8324
      - 192.168.50.238::32469
      - 192.168.50.238::32410/udp
      - 192.168.50.238::32412/udp
      - 192.168.50.238::32413/udp
      - 192.168.50.238::32414/udp
    restart: unless-stopped
    pull_policy: build
    deploy:
      labels:
        # traefik.enable: "false"
        # traefik.port: "32400"
        # traefik.frontend.rule: "Host:plex.molovestoshare.com"
        # traefik.backend: plex
        com.centurylinklabs.watchtower.enable: "true"
        org.label-schema.group: "ums-svcs"


# networks:
#   fast_net:
#     attachable: true
#     driver: macvlan
#     driver_opts:
#       parent: wlan0  #target interface
#     ipam:
#       config:
#         - subnet: 192.168.0.0/16 # change this
#           ip_range: 192.168.0.0/24
#           # aux_addresses:   # Auxiliary IPv4 or IPv6 addresses used by Network driver, as a mapping from hostname to IP
#             # host1: 192.168.0.10
#     external: true
#     labels:
#       com.label-schema.group: "ums-svcs"