# Title:
# Description: Plex Media Server
# IconURL: https://play-lh.googleusercontent.com/F39M_Ce9OBW62qntNOq6jvUH3Nh0N-03eGNFFU14GAU-hCU0RlHBONYYBiS-0SY0kaY
---
version: '3.9'

volumes:
  plex-ums: {}

services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    hostname: ums-plex
    domainname: plex.molovestoshare.com
    privileged: true
    cap_add:
      - DAC_READ_SEARCH
      - SYS_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - TZ="America/Chicago"
      - runtime=nvidia
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:plex
      - TP_DOMAIN=themepark.molovestoshare.com
      - TP_THEME=overseerr
      - PLEX_CLAIM= # Generate new claim codes here: https://www.plex.tv/claim/
      - ADVERTISE_IP="http://192.168.50.34:32400/" # dont forget to add '/web' to the url
    volumes:
      - /tmp:/transcodes
      - /dev/dri:/dev/dri
      - plex-ums:/config
      - /home/monash/th_stordsk/Media/tv-shows:/TH-TV_Shows
      - /home/monash/th_stordsk/Media/movies:/TH-Movies
      - /home/monash/tf_stordsk/Media/tv-shows:/TF-TV_Shows
      - /home/monash/tf_stordsk/Media/movies:/TF-Movies
      
    #network_mode: host
    ports:
      - 32400:32400
      - :1900/udp
      - :3005
      - :5353/udp
      - :8324
      - :32469
      - :32410/udp
      - :32412/udp
      - :32413/udp
      - :32414/udp
    restart: unless-stopped
    deploy:
      labels:
        com.example.description: "ums"