# Title:
# Description: Plex Media Server
# IconURL: https://play-lh.googleusercontent.com/F39M_Ce9OBW62qntNOq6jvUH3Nh0N-03eGNFFU14GAU-hCU0RlHBONYYBiS-0SY0kaY
# NOTES: OS networking needs to have the macvlan sysmodule enabled: sudo modprobe macvlan && sudo lsmod | grep macvlan
# NOTES: create macvlan docker network: docker network create -d macvlan --subnet 172.19.0.0/16 --gateway 172.19.0.1 --ip-range 172.19.0.10/28 --aux-address 'host=172.19.0.10' -o parent=wlan0 -o macvlan_mode=bridge macvlan_wlan0
---
version: '3.9'

volumes:
  plex_data: {}

services:
  plex:
    privileged: true
    image: lscr.io/linuxserver/plex
    container_name: ums-plex
    hostname: ums-plex
    domainname: plex.molovestoshare.com
    cap_add:
      - DAC_READ_SEARCH
      - SYS_ADMIN
    environment:
      - PLEX_UID=${PUID:-1000}
      - PLEX_GID=${GUID:-1000}
      - VERSION=docker
      - TZ="America/Chicago"
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:plex
      - TP_COMMUNITY_THEME=true
      - TP_THEME=onedark #overseerr - case sensitive Infinity Stone Themes: mind (yellow), reality (red), space (blue), soul (orange), power (purple),time (green), ibracorp 
      #- PLEX_CLAIM=claim-AjzLYsyhnD_gzSdzy8Md # Generate new claim codes here: https://www.plex.tv/claim/
    volumes:
      - /tmp:/transcodes
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
      - plex_data:/config
      - /mnt/tf_nfsdisk/Media/tv-shows:/TV Shows
      - /mnt/tf_nfsdisk/Media/movies:/Movies
    network_mode: host
    ports:
      - 192.168.50.239:32400:32400
      - 192.168.50.239::1900/udp
      - 192.168.50.239::3005
      - 192.168.50.239::5353/udp
      - 192.168.50.239::8324
      - 192.168.50.239::32469
      - 192.168.50.239::32410/udp
      - 192.168.50.239::32412/udp
      - 192.168.50.239::32413/udp
      - 192.168.50.239::32414/udp
    restart: unless-stopped
    deploy:
      # replicas: 2
      labels:
        com.centurylinklabs.watchtower.enable: "true"
        org.label-schema.group: "ums-svcs"
        # traefik.enable: "false"
        # traefik.port: "32400"
        # traefik.frontend.rule: "Host:plex.molovestoshare.com"
        # traefik.backend: plex
