# Title:
# Description: Plex Media Server
# IconURL: https://play-lh.googleusercontent.com/F39M_Ce9OBW62qntNOq6jvUH3Nh0N-03eGNFFU14GAU-hCU0RlHBONYYBiS-0SY0kaY
---
version: '3.9'

volumes:
  plex_data: {}

services:
  plex:
    privileged: true
    image: linuxserver/plex
    container_name: ums-plex
    hostname: ums-plex
    domainname: plex.molovestoshare.com
    cap_add:
      - DAC_READ_SEARCH
      - SYS_ADMIN
    environment:
      - PLEX_UID=${PUID:-1000}
      - PLEX_GID=${GUID:-1000}
      - VERSION=docker
      - TZ="America/Chicago"
      - runtime=nvidia
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:plex
      - TP_DOMAIN=themepark.molovestoshare.com
      - TP_THEME=overseerr
      # - PLEX_CLAIM= # Generate new claim codes here: https://www.plex.tv/claim/
      # - ADVERTISE_IP= # dont forget to add '/web' to the url
    volumes:
      - /tmp:/transcodes
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
      - plex_data:/config
      - /mnt/tf_nfsdisk/Media/tv-shows:/TV Shows
      - /mnt/tf_nfsdisk/Media/movies:/Movies
    network_mode: host
    ports:
      - 32400:32400
      - :1900/udp
      - :3005
      - :5353/udp
      - :8324
      - :32469
      - :32410/udp
      - :32412/udp
      - :32413/udp
      - :32414/udp
    restart: unless-stopped
    pull_policy: build
    deploy:
      labels:
        # traefik.enable: "false"
        # traefik.port: "32400"
        # traefik.frontend.rule: "Host:plex.molovestoshare.com"
        # traefik.backend: plex
        com.centurylinklabs.watchtower.enable: "true"
        org.label-schema.group: "ums-svcs"
