# Title: statping
# Desc: Statping - Web and App Status Monitoring for Any Type of Project
# Icon URL: https://s3-us-west-2.amazonaws.com/gitimgs/statping.png
---
version: '2.3'

services:
  statping:
    container_name: statping
    image: statping/statping
    restart: always
    volumes:
      - statping_data:/app
    environment:
      DB_CONN: sqlite
    ports:
      - 8080:8080
    pull_policy: build
    deploy:
      labels:
        com.example.description: "monitoring"

volumes:
  statping_data:
