# Title: statping
# Desc: Statping - Web and App Status Monitoring for Any Type of Project
# Icon URL: https://s3-us-west-2.amazonaws.com/gitimgs/statping.png
---
version: '2.3'

volumes:
  statping_data:

services:
  statping:
    container_name: statping
    image: statping/statping
    restart: always
    volumes:
      - statping_data:/app
    environment:
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - AUTH_USERNAME=${AUTH_USERNAME}
      - AUTH_PASSWORD=${AUTH_PASSWORD}
      - DB_CONN=${DB_CONN}
      - API_SECRET=${ADMIN_PASSWORD}
      - USE_CDN=${USE_CDN}
      - USE_ASSETS=${USE_ASSETS}
      - IS_DOCKER=${IS_DOCKER}
      - IS_AWS=${IS_AWS}
      - SASS=${SASS}
      - CMD_FILE=${CMD_FILE}
    ports:
      - 8080:8080
    deploy:
      labels:
        com.example.description: "monitoring"