version: '2.3'

volumes:
  statping_data: {}

services:
  statping:
    container_name: statping
    image: statping/statping:latest
    domainname: appstatus.molovestoshare.com
    env_file:
      - .env
    restart: always
    volumes:
      - statping_data:/app
      - ./utils:/app
    environment:
      DB_CONN: sqlite
      ADMIN_USER: "${ADMIN_USER:-default}" #${VAR:-default} 
      ADMIN_PASSWORD: "${ADMIN_PASSWORD:-default}"
      DESCRIPTION: "${DESCRIPTION:-default}"
    ports:
      - 8080:8080