name: statping

volumes:
  statping_data: {}

services:
  statping:
    cpu_shares: 90
    command: []
    container_name: statping
    deploy:
      resources:
        limits:
          memory: 3790M
    environment:
      - ADMIN_EMAIL=monash@mystatping.com
      - ADMIN_PASSWORD=~Z0vJE8Q_S4wezp6r@)u>9:52N/T\lM1
      - ADMIN_USER=monash
      - API_SECRET=~Z0vJE8Q_S4wezp6r@)u>9:52N/T\lM1
      - DESCRIPTION=Self-Hosted Application Health Monitoring
      - DOMAIN=https://appstatus.molovestoshare.com
      - NAME=StatPing App Monitoring
    hostname: statping
    image: statping/statping:latest
    ports:
      - mode: ingress
        target: 8080
        published: "8080"
        protocol: tcp
    privileged: true
    restart: always
    volumes:
      - type: volume
        target: /app
        source: statping_data
      - type: bind
        source: /home/ubuntu/Git/self-hosted-stacks/statping/utils/services.yml
        target: /app/services.yml
        bind:
          create_host_path: true
    devices: []
    cap_add: []
    networks:
      - default
networks:
  default:
    name: statping_default
x-casaos:
  author: self
  category: self
  hostname: appstatus.molovestoshare.com
  icon: https://avatars.githubusercontent.com/u/88886654?v=4
  index: /
  port_map: ""
  scheme: http
  title:
    custom: StatPing Monitoring
