{
 "title": "internet connection",
 "tags": [
  "speedtest",
  "ping"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Download Bandwidth [D/L]",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upload Bandwidth [U/L]",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "speedtest_upload_bits_per_second",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Speedtest ping latency",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "speedtest_ping_latency_milliseconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packets Per Second [U/D]",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second",
     "legendFormat": "__auto"
    },
    {
     "expr": "speedtest_upload_bits_per_second",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Target Response Times",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 9 },
   "repeat": "host",
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}