# Title: gitea-on-docker
# Description: Gitea is a painless, self-hosted, all-in-one software development service.
# Icon URL: https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Gitea_Logo.svg/1200px-Gitea_Logo.svg.png
# NOTES: App using PSQL and Host Vol

version: "3"

services:
  srv:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea-srv:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
     - "8080:3000"
     - "2221:22"
    labels:
      org.label-schema.group: "dev-tools"
      com.centurylinklabs.watchtower.enable: "true"
  db:
    image: postgres:14
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - gitea
    volumes:
      - ./psql:/var/lib/postgresql/data
    labels:
      org.label-schema.group: "dev-tools"
      com.centurylinklabs.watchtower.enable: "true"

volumes:
  gitea:
    driver: local

networks:
  gitea:
    external: false