# Title: watchtower
# Description: A container-based solution for automating Docker container base image updates.
# Icon URL: https://containrrr.dev/watchtower/images/logo-450px.png
# NOTE: Multiple instances can't run with the same scope; An instance without a scope will clean up other running instances, even if they have a defined scope
version: '3.9'
services:
  watchtower:
    container_name: watchtower
    privileged: true
    image: containrrr/watchtower # or containrrr/watchtower:arm64v8-latest
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_REMOVE_VOLUMES=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    labels:
      org.label-schema.group: "mgmt-tools"
      com.centurylinklabs.watchtower.enable: "true"