version: '2.3'
name: watchtower
services:
  main_app:
    cpu_shares: 45
    command: []
    container_name: tc-watchtower
    deploy:
      resources:
        limits:
          memory: 3790M
    environment:
      - WATCHTOWER_CLEANUP=true
    hostname: tc-watchtower
    image: containrrr/watchtower:arm64v8-latest
    labels:
      icon: https://icon.casaos.io/main/all/watchtower.png
    ports:
      - target: 80
        published: "3080"
        protocol: tcp
      - target: 443
        published: "3443"
        protocol: tcp
    privileged: true
    restart: always
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    devices: []
    cap_add: []
    network_mode: bridge
x-casaos:
  author: self
  category: self
  icon: https://icon.casaos.io/main/all/watchtower.png
  index: /
  port_map: ""
  scheme: http
  store_app_id: Watchtower
  title:
    custom: Watchtower