# Title: homer
# Description: MoLovesToShare Dashboard
# IconURL: https://icons.iconarchive.com/icons/jonathan-rey/simpsons/256/Homer-Simpson-02-Donut-icon.png
version: '3.9'
volumes:
  container_data: {}
services:
  homer:
    image: b4bz/homer:latest
    container_name: homer
    hostname: homer
    environment:
      - INIT_ASSETS=1 # default 0
      - TZ=America/Chicago
      - PORT=8080
    volumes:
      - container_data:/www/assets
    ports:
      - 8080:8080
    user: 1000:1000 # 1000 default
    restart: always
  