version: "3"
services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.5.0
    container_name: node_exporter
    hostname: node_exporter
    command: '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave
  cadvisor:
    privileged: true
    container_name: cadvisor
    hostname: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    network_mode: "host"
    ports:
      - "8080:8080"
    volumes: 
      - "/:/rootfs"
      - "/var/run:/var/run"
      - "/sys:/sys"
      - "/var/lib/docker/:/var/lib/docker"
      - "/dev/disk/:/dev/disk"
    devices: 
      - "/dev/kmsg"
    labels:
      org.label-schema.group: "monitoring"
      com.centurylinklabs.watchtower.enable: "true"
      # traefik.enable: "false"
      # traefik.port: "3000"
      # traefik.frontend.rule: "Host:$HOST-cadvisor.molovestoshare.com"
      # traefik.backend: grafpromon