# Title: cadvisor
# Description: Container Advisor is an open-source tool developed by Google to monitor containers. 
# Icon URL: https://linuxaws.files.wordpress.com/2022/03/cadvisor.png?w=339
version: "3"
services:
  node_exporter:
    cap_add:
      - ALL
    image: quay.io/prometheus/node-exporter
    container_name: node_exporter
    hostname: node_exporter
    pid: host
    restart: unless-stopped
    volumes:
      - /sys:/host/sys:ro,rslave #ro1
      - /proc:/host/proc:ro,rslave #ro1
      - /:/rootfs:ro,rslave #ro1
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
  cadvisor:
    privileged: true
    container_name: cadvisor
    hostname: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    network_mode: "host"
    ports:
      - "8080:8080"
    command:
      - '-port=8098'
    volumes: 
      - "/:/rootfs"
      - "/var/run:/var/run"
      - "/sys:/sys"
      - "/var/lib/docker/:/var/lib/docker"
      - "/dev/disk/:/dev/disk"
      - "/cgroup:/cgroup:ro"
    devices: 
      - "/dev/kmsg"
    labels:
      org.label-schema.group: "monitoring"
      com.centurylinklabs.watchtower.enable: "true"
      # traefik.enable: "false"
      # traefik.port: "3000"
      # traefik.frontend.rule: "Host:$HOST-cadvisor.molovestoshare.com"
      # traefik.backend: grafpromon