version: "3"
services:
  cadvisor:
    privileged: true
    container_name: cadvisor
    hostname: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    network_mode: "host"
    ports:
      - "8080:8080"
    volumes: 
      - "/:/rootfs"
      - "/var/run:/var/run"
      - "/sys:/sys"
      - "/var/lib/docker/:/var/lib/docker"
      - "/dev/disk/:/dev/disk"
    devices: 
      - "/dev/kmsg"
    labels:
      org.label-schema.group: "monitoring"
      com.centurylinklabs.watchtower.enable: "true"
      # traefik.enable: "false"
      # traefik.port: "3000"
      # traefik.frontend.rule: "Host:$HOST-cadvisor.molovestoshare.com"
      # traefik.backend: grafpromon