# The root route on which each incoming alert enters.
route:
  # The root route must not have any matchers as it is the entry point for
  # all alerts. It needs to have a receiver configured so alerts that do not
  # match any of the sub-routes are sent to someone.
  receiver: 'mail'
  repeat_interval: 4h
  group_by: [ alertname ]


receivers:
  - name: 'mail'
    email_configs:
      - smarthost: 'smtp.gmail.com:465'
        auth_username: 'maurice.nash1@gmail.com'
        auth_password: ${ALERTMANAGER_EMAIL_PASSWORD:-passwd}
        from: 'admin@molovestoshare.com'
        to: 'maurice.nash@icloud.com'