# NOTE Portainer creates a fake mount point for docker compose stacks. The actual location is /var/lib/docker/volumes/

name: portainer
services:
  portainer:
    cpu_shares: 90
    command: []
    container_name: mgmt-stack-portainer
    deploy:
      resources:
        limits:
          memory: 3790M
    hostname: portainer
    image: portainer/portainer-ee:latest
    ports:
      - mode: ingress
        target: 9000
        published: "32772"
        protocol: tcp
    privileged: true
    restart: always
    pull_policy: build
    volumes:
      - type: bind
        source: /data/compose/portainer
        target: /data
        bind:
          create_host_path: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        bind:
          create_host_path: true
    devices: []
    cap_add: []
    environment: []
    networks:
      - portainer
networks:
  portainer:
    name: portainer
x-casaos:
  author: self
  category: self
  hostname: portainer.molovestoshare.com
  icon: https://linuxiac.b-cdn.net/wp-content/uploads/2023/06/portainer.jpg
  index: /
  port_map: ""
  scheme: http
  title:
    custom: Portainer Docker UI
