# Title: homebridge-on-docker
# Description: HomeKit API for the Impatient
# Icon URL: https://raw.githubusercontent.com/homebridge/branding/master/logos/homebridge-color-round-stylized.png
# NOTES: container missing bluez-hcidump pkg

version: '2'

volumes:
  homebridge_data: {}

services:
  homebridge:
    build:
      context: .
      dockerfile: /home/monash/Git/self-hosted-stacks/homebridge/Dockerfile
    privileged: true
    container_name: homebridge
    domainname: homebridge.molovestoshare.com
    image: oznu/homebridge #homebridge/homebridge #oznu/homebridge
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dev/bus/usb:/dev/bus/usb
      - homebridge_data:/homebridge
    network_mode: host
    ports:
      - 8581:8581
    logging:
      driver: json-file
      options:
        max-size: "50mb"
        max-file: "1"
    restart: always
    labels:
      org.label-schema.group: "automation"