# Title: homebridge-on-docker
# Description: HomeKit API for the Impatient
# Icon URL: https://raw.githubusercontent.com/homebridge/branding/master/logos/homebridge-color-round-stylized.png
# NOTES: OS networking needs to have the macvlan sysmodule enabled: sudo modprobe macvlan && sudo lsmod | grep macvlan
# NOTES: create macvlan docker network: docker network create -d macvlan --subnet 172.29.0.0/16 --gateway 172.29.0.1 --ip-range 172.29.0.10/28 --aux-address 'host=172.29.0.10' -o parent=enp66s0 -o macvlan_mode=bridge macvlan_eth0
# NOTES: To allow communication between the Docker containers and the default gateway:  sudo ip link set dev <dev-name> promisc on
# NOTES: one last problem: sudo ip link add macvlan_int link enp0s3 type macvlan mode bridge

version: '2'

volumes:
  homebridge_data: {}

services:
  homebridge:
    privileged: true
    container_name: homebridge
    domainname: homebridge.molovestoshare.com
    image: oznu/homebridge
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - homebridge_data:/homebridge
    network_mode: host
    ports:
      - 8581:8581
    logging:
      driver: json-file
      options:
        max-size: "50mb"
        max-file: "1"
    restart: always
    pull_policy: build
    labels:
      org.label-schema.group: "automation"