{
 "title": "🌊🪣🌡️🏕️🦉 DWC Tent Status and Monitoring",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Live🔴Hydro🪣Temperature🌡️Prediction🔮",
   "type": "stat",
   "description": "Predictions based on ± .1 degree change",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dwc_temp_monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"http_listener_v2\" and\r\n    r._field == \"temperature\"\r\n  )\r\n  |> aggregateWindow(every: 1m, fn: mean)\r\n  |> derivative(unit: 1m, nonNegative: false)\r\n  |> last()\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      trend_code:\r\n        if r._value > 0.1 then 1\r\n        else if r._value < -0.05 then -1\r\n        else 0\r\n    }))\r\n  |> keep(columns: [\"_time\", \"trend_code\"])\r\n"
    }
   ]
  },
  {
   "title": "Live🔴Hydro🪣Water💧Temperature🌡️ ",
   "type": "gauge",
   "description": "### Optimal DWC Reservoir Temperature Range\n- <17°C 🥶Roots can stunt, slow growth\n- 18-20°C 😍Max O₂, low root rot risk \n- 21–22°C 😎“OK” with bennies\n- 23–24°C 🦠pathogens for root rot\n- 25–26°C 👹Fast root rot, O₂ drops\n- <26°C ☠️Pathogens thrive, Roots suffocate\n",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dwc_temp_monitoring\")\r\n  |> range(start: -15m)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"http_listener_v2\" and\r\n    r._field == \"temperature\" and\r\n    r.source == \"dwc_r4wifi\"\r\n  )\r\n  |> sort(columns: [\"_time\"], desc: true)\r\n  |> limit(n: 1)\r\n  |> keep(columns: [\"_value\", \"_time\"])\r\n"
    }
   ]
  },
  {
   "title": "Relative⬅️➡️Hydro🪣Tempature🌡️History📜",
   "type": "piechart",
   "description": "too hot 🥵🦠👹 || too cold 🥶❄️🧊 || just right 😍🥰☺️",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"dwc_temp_monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"http_listener_v2\" and\r\n    r._field == \"temperature\"\r\n  )\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      category: if r._value < 17.0 then \"too cold 🥶❄️🧊\"\r\n                else if r._value < 23.0 then \"just right 😍🥰☺️\"\r\n                else \"too hot 🥵🦠👹\"\r\n    }))\r\n  |> group(columns: [\"category\"])\r\n  |> count(column: \"_value\")\r\n  |> rename(columns: { _value: \"Temps were\" })\r\n  |> keep(columns: [\"category\", \"Temps were\"])\r\n"
    }
   ]
  },
  {
   "title": "Hydro🪣Temperature🌡️Stats📊",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"dwc_temp_monitoring\")\r\n  |> range(start: v.timeRangeStart)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"http_listener_v2\" and\r\n    r._field == \"temperature\"\r\n  )\r\n  |> aggregateWindow(every: 200s, fn: last, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\r\n  |> yield(name: \"30s_points\")\r\n"
    }
   ]
  },
  {
   "title": "🚿♻️Next Res Change In🪣⏱️",
   "type": "stat",
   "description": "countdown to reservoir change",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "lastReset = from(bucket: \"dwc_temp_monitoring\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) =>\r\n      r._measurement == \"week_reset\" and\r\n      r._field == \"value\"\r\n    )\r\n  |> last()\r\n\r\nlastReset\r\n  |> map(fn: (r) => ({\r\n      time_left_hours: 168.0 - float(v: uint(v: now()) - uint(v: r._time)) / 3600000000000.0\r\n    }))\r\n  |> keep(columns: [\"time_left_hours\"])\r\n"
    }
   ]
  },
  {
   "title": "🛑🧊Ice Free Streak❄️😎",
   "type": "stat",
   "description": "How Long it's Been since I've had to put Ice in the Bucket",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dwc_temp_monitoring\")\r\n  |> range(start: -100y)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"manual_cooling_events\" and\r\n    r._field == \"value\"\r\n  )\r\n  |> sort(columns: [\"_time\"], desc: true)\r\n  |> limit(n: 1)\r\n  |> map(fn: (r) => ({\r\n    _time: now(),\r\n    _value: float(v: uint(v: now()) - uint(v: r._time)) / 3600000000000.0\r\n  }))\r\n"
    }
   ]
  },
  {
   "title": "Hydro🪣Temperature🌡️Stats📊",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"dwc_temp_monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"http_listener_v2\" and\r\n    r._field == \"temperature\"\r\n  )\r\n  |> aggregateWindow(every: 22m, fn: last, createEmpty: false)\r\n  // — keep only time, value, and field (remove the “source” tag)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\r\n  |> yield(name: \"30m-points\")\r\n"
    }
   ]
  },
  {
   "title": "Hydro🪣Temperature🌡️Stats📊",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"dwc_temp_monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"http_listener_v2\" and\r\n    r._field == \"temperature\"\r\n  )\r\n  |> aggregateWindow(every: 53m, fn: last, createEmpty: false)\r\n  // — keep only time, value, and field (remove the “source” tag)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\r\n  |> yield(name: \"30m-points\")\r\n"
    }
   ]
  },
  {
   "title": "Hydro🪣Temperature🌡️Stats📊",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"dwc_temp_monitoring\")\r\n  |> range(start: v.timeRangeStart)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"http_listener_v2\" and\r\n    r._field == \"temperature\"\r\n  )\r\n  |> aggregateWindow(every: 12h, fn: last, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\r\n  |> yield(name: \"1m_points\")\r\n"
    }
   ]
  },
  {
   "title": "Hydro🪣Water💧Temperature🌡️Distribution🧮History📜",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"dwc_temp_monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n      r._measurement == \"http_listener_v2\" and\r\n      r._field       == \"temperature\"\r\n    )\r\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) }))\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> yield(name: \"hourly_temps\")\r\n"
    }
   ]
  }
 ]
}