# Title: grafpromon
# Description: A monitoring solution for Docker hosts and containers with Prometheus, Grafana, cAdvisor, NodeExporter and alerting with Statping
# Icon URL: https://i.imgur.com/ptSbnTa.png
version: '3.8'
networks:
  monitoring:
    driver: bridge
volumes:
  graf_data: {}
  prom_data: {}
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - ./data:/prometheus
    restart: unless-stopped
  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    ports:
      - '3000:3000'
    volumes:
      - graf_data:/var/lib/grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_USERS_ALLOW_SIGN_UP=false
  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.5.0
    container_name: node_exporter
    hostname: node_exporter
    command: '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave
  cadvisor:
    privileged: true
    image: gcr.io/cadvisor/cadvisor:latest #gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: cadvisor
    hostname: cadvisor
    command:
      - '-port=8098'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    restart: unless-stopped

    labels:
      org.label-schema.group: "monitoring"
      com.centurylinklabs.watchtower.enable: "true"
      # traefik.enable: "false"
      # traefik.port: "3000"
      # traefik.frontend.rule: "Host:grafpromon.molovestoshare.com"
      # traefik.backend: grafpromon