version: '3.9'

services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard-standalone
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/CDT
      - SERVERURL=wireguard.molovestoshare.com
      - SERVERPORT=51820
      - PEERS=1
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0
    volumes:
      - /home/monash/tf_stordsk/Docker/wireguard/standalone-proxy/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
    restart: unless-stopped