x-tcpservice: &tcpservice
  type: tcp
  check_interval: 60
  timeout: 15
  allow_notifications: true
  notify_after: 0
  notify_all_changes: false
  public: true
  redirect: true

x-httpservice: &httpservice
  type: http
  method: GET
  check_interval: 45
  timeout: 10
  expected_status: 200
  allow_notifications: true
  notify_after: 2
  notify_all_changes: false
  public: true
  redirect: true

services:

  - name: Portainer Container Management
    domain: 192.168.50.193
    port: 2376
    <<: *tcpservice

  - name: Statping Health Monitoring
    domain: https://appstatus.molovestoshare.com
    <<: *httpservice

  - name: Homebridge - Home Automation
    domain: https://homebridge.molovestoshare.com
    <<: *httpservice

  - name: Plex - Media Server
    domain:  https://plex.molovestoshare.com/web/index.html
    port: 32400
    <<: *tcpservice

  - name: Deluge - Ultimate Media Stack
    domain: https://ums-proxy.molovestoshare.com
    <<: *httpservice

  - name: Prowlarr - Ultimate Media Stack Indexer
    domain: https://prowlarr.molovestoshare.com
    <<: *httpservice

  - name: Sonarr - Ultimate Media Stack TV Show Manager
    domain: https://sonarr.molovestoshare.com
    <<: *httpservice

  - name: Radarr - Ultimate Media Stack Movie Manager
    domain: https://radarr.molovestoshare.com
    <<: *httpservice
