# Title: themepark-on-docker
# Desc: A collection of themes/skins for your favorite apps!
# Icon URL: https://docs.theme-park.dev/site_assets/logo.png
---
version: '3.9'
services:
  theme-park:
    image: gilbn/theme.park:latest
    container_name: theme-park
    hostname: ums-themepark
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - TP_URLBASE=themepark.molovestoshare.com #optional
      - TP_DOMAIN=themepark.molovestoshare.com #optional
    volumes:
      - /data/compose/ums-themepark:/config #optional
    ports:
      - 8980:80
      - 4943:443
    restart: unless-stopped
